logging:
 level:
  org.springframework.security: DEBUG

server:
  port: 9002
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: https://microservice-registry-sisdoe.herokuapp.com/eureka
  metadataMap:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

auth:
 server:
  url: https://oauth-server-sisdoe.herokuapp.com/uaa/oauth/check_token/
  clientId: sisdoeResultadoExameClient
  clientsecret: secret

security:
  user:
    password: mySecretKey
  oauth2:
    client:
      accessTokenUri: https://oauth-server-sisdoe.herokuapp.com/uaa/oauth/token
      userAuthorizationUri: https://oauth-server-sisdoe.herokuapp.com/uaa/oauth/authorize
      clientId: sisdoeResultadoExameClient
      clientSecret: secret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwR84LFHwnK5GXErnwkmDmPOJl4CSTtYXCqmCtlbF+5qVOosu0YsM2DsrC9O2gun6wVFKkWYiMoBSjsNMSI3Zw5JYgh+ldHvA+MIex2QXfOZx920M1fPUiuUPgmnTFS+Z3lmK3/T6jJnmciUPY1peh4MXL6YzeI0q4W9xNBBeKT6FDGpduc0FC3OlXHfLbVOThKmAUpAWFDwf9/uUA//l3PLchmV6VwTcUaaHp5W8Af/GU4lPGZbTAqOxzB9ukisPFuO1DikacPhrOQgdxtqkLciRTa884uQnkFwSguOEUYf3ni8GNRJauIuW0rVXhMOs78pKvCKmo53M0tqeC6ul+QIDAQAB
          -----END PUBLIC KEY-----

ribbon:
  eureka:
    enabled: true