server:
  port: 8888

eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: microservice-registry-sisdoe.herokuapp.com
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}/eureka/
      
spring.cloud.config.discovery.enabled: true